---
# file: roles/rabbitmq/tasks/clustering.yml
- name: Killing all RabbitMQ processes
  shell:
    pkill -9 -u rabbitmq || true

- name: Cleaning RabbitMQ app everywhere 
  file:
    path=/var/lib/rabbitmq/mnesia
    state=absent

- name: Starting RabbitMQ service on the master node
  service:
    name=rabbitmq-server
    state=restarted
  when: inventory_hostname == master

- name: Starting RabbitMQ App only on master node
  command:
    /usr/sbin/rabbitmqctl start_app
  when: inventory_hostname == master

- name: Set the RabbitMQ cluster name
  command:
    /usr/sbin/rabbitmqctl set_cluster_name "{{ rabbitmq_cluster_name }}"
  when: inventory_hostname == master

- name: Starting RabbitMQ service everywhere
  service:
    name=rabbitmq-server
    state=restarted
  when: inventory_hostname != master

- name: Stopping the RabbitMQ application
  command: /usr/sbin/rabbitmqctl stop_app
  when: inventory_hostname != master

- pause:
    prompt="Waiting few seconds..."
    seconds=5

- name: Making slave nodes joining the RabbitMQ cluster
  command:
    /usr/sbin/rabbitmqctl join_cluster "rabbit@{{ rabbitmq_master_name }}"
  when: inventory_hostname != master

- name: Starting RabbitMQ App only on slave node(s)
  command:
    /usr/sbin/rabbitmqctl start_app
  when: inventory_hostname != master

- name: Finalizing the setup by creating file /etc/rabbitmq/clustered
  copy:
    content="Cluster created:{{ ansible_date_time.date }}"
    dest=/etc/rabbitmq/clustered
    owner="{{ rabbitmq_user }}"
    group="{{ rabbitmq_group }}"
