---
# file: roles/rabbitmq/tasks/erlang.yml
- name: Set Erlang cookie between  each RabbitMQ node
  copy:
    content="{{ rabbitmq_erlang_cookie }}"
    dest=/var/lib/rabbitmq/.erlang.cookie
    owner="{{ rabbitmq_user }}"
    group="{{ rabbitmq_group }}"
    mode=0400
  register: erlang_cookie
  
- name: delete database when cookie is changed
  file:
    dest: /var/lib/rabbitmq/mnesia
    state: absent
  when: erlang_cookie.changed and rabbitmq_reset_cluster