---
# file: roles/rabbitmq/tasks/install.yml
- name: Install RabbitMQ packages
  apt: name=rabbitmq-server state=latest update_cache=yes
  tags: rabbitmq-package

- name: Enable RabbitMQ service
  service: name=rabbitmq-server enabled=yes
  tags: rabbitmq-service
