---
# file: roles/rabbitmq/tasks/install.yml
- name: Install RabbitMQ packages (Debian family)
  apt:
    name=rabbitmq-server
    state=latest
    update_cache=yes
  when: ansible_os_family == 'Debian'
  tags:
    - rabbitmq
    - rabbitmq-package

- name: Install RabbitMQ packages (RedHat family)
  yum:
    name="{{ item }}"
    state=present
  with_items: "{{ rabbitmq_rh_packages }}"
  notify: systemctl reload
  when: ansible_os_family == 'RedHat'
  tags:
    - rabbitmq
    - rabbitmq-package
