---
# file: roles/rabbitmq/tasks/install.yml
- name: Install RabbitMQ packages (Debian)
  apt:
    name=rabbitmq-server
    state=latest
    update_cache=yes
  when: ansible_distribution == 'Debian'
  tags:
    - rabbitmq
    - rabbitmq-package

- name: Install RabbitMQ packages (CentOS)
  yum:
    name="{{ item }}"
    state=present
  with_items: "{{ rabbitmq_packages }}"
  notify: systemctl reload
  when: ansible_distribution == 'CentOS'
  tags:
    - rabbitmq
    - rabbitmq-package

- name: Enable RabbitMQ service
  service:
    name=rabbitmq-server
    enabled=yes
  tags:
    - rabbitmq
    - rabbitmq-package
