---
# file: roles/rabbitmq/tasks/limits.yml
- name: Creating systemd RabbitMQ service definition
  file:
    path=/etc/systemd/system/rabbitmq-server.service.d
    state=directory

- name: Increasing file descriptors limit via Systemd
  template:
    src=etc/systemd/system/rabbitmq-server.service.d/limits.conf
    dest=/etc/systemd/system/rabbitmq-server.service.d/limits.conf
    mode=0644
  register: service_limit

- name: systemctl reload
  command: systemctl --system daemon-reload
  when: service_limit.changed