---
# file: roles/rabbitmq/tasks/main.yml
- include: repository.yml
- include: install.yml
- include: erlang.yml
- include: configuration.yml
- include: limits.yml

- name: Checking if a RabbitMQ cluster already exists
  stat: path=/etc/rabbitmq/clustered
  register: clustered

- include: clustering.yml
  when: rabbitmq_reset_cluster and rabbitmq_clustering or (clustered.stat.exists != True) and rabbitmq_clustering

- include: plugins.yml
- include: vhosts.yml
- include: users.yml
