---

- name: create rabbitmq in pacemaker
  pcs_resource: command=create resource_id=rabbitmq type=ocf:heartbeat:rabbitmq-cluster clone=true
  args:
    options:
      set_policy: "ha-all ^(?!amq\\.).* {\"ha-mode\":\"all\"}"
    operations:
      - action: monitor
        options:
          interval: 10
          timeout: 40
      - action: start
        options:
          interval: 0s
          timeout: 200s
      - action: stop
        options:
          interval: 0s
          timeout: 200s
    metas:
      notify: true
  run_once: true
- name: update rabbitmq-clone in pacemaker
  pcs_resource: command=update resource_id=rabbitmq-clone type=ocf:heartbeat:rabbitmq-cluster clone=true
  args:
    metas:
      interleave: true
      ordered: true
  run_once: true
