---

- name: create rabbitmq in pacemaker
  pcs_resource: command=create resource_id=rabbitmq type=ocf:rabbitmq:rabbitmq-server-ha master=true
    operations:
      - action: monitor
        options:
          interval: 10
          timeout: 40
      - action: monitor
        options:
          interval: 20
          role: Master
          timeout: 40
      - action: start
        options:
          interval: 0s
          timeout: 200s
      - action: stop
        options:
          interval: 0s
          timeout: 200s
    metas:
      migration-threshold: 10
      failure-timeout: "30s"
      resource-stickiness: 100
  run_once: true
