---
# files: roles/rabbitmq/tasks/plugins.yml
- name: Enabling RabbitMQ management plugin
  rabbitmq_plugin:
    names=rabbitmq_management
    state=enabled
    new_only=yes
  when: rabbitmq_management_plugin is defined and
        rabbitmq_management_plugin
